packages:
  - 'libs/*'
  - 'apps/*'
  - 'dev-apps/*'
  - 'scripts/*'

onlyBuiltDependencies:
  - lefthook
  - turbo
  - esbuild
  - core-js-pure

catalogs:
  common:
    tailwindcss: '^4.1.18'
    "@tailwindcss/vite": "^4.1.18"
    typescript: '^5.7.3'
    tw-animate-css: "^1.4.0"

  web:
    vite: '^7.3.1'

  react:
    '@types/react': '^19.2.5'
    '@types/react-dom': '^19.2.3'
    react: '^19.2.3'
    react-dom: '^19.2.3'
    "@vitejs/plugin-react": "^5.1.2"

  service:
    effect: '^3.19.15'
    '@types/node': '^24.10.1'
  
  package:
    unbuild: '3.6.1'

