packages:
  - 'libs/*'
  - 'apps/*'
  - 'dev-apps/*'
  - 'scripts/*'

onlyBuiltDependencies:
  - lefthook
  - turbo
  - core-js-pure

catalogs:
  web:
    vite: '^7.3.1'
  react:
    '@types/react': '^19.2.5'
    '@types/react-dom': '^19.2.3'
    react: '^19.2.0'
    react-dom: '^19.2.0'

  # fonts:
  package:
    typescript: '^5.7.3'
    unbuild: '3.6.1'

